version: '3'

services:
  db:
    container_name: db_yes_sample
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=yes-sample
      - MYSQL_USER=yes-sample
      - MYSQL_PASSWORD=yes-sample
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    container_name: phpmyadmin_yes_sample
    image: phpmyadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma-yes-sample.entrypoints=websecure
      - traefik.http.routers.pma-yes-sample.rule=Host(`pma.yes-sample.local`)
    environment:
      - PMA_HOST=db
      - PMA_USER=yes-sample
      - PMA_PASSWORD=yes-sample
    depends_on:
      - db
    networks:
      - web

  web:
    container_name: web_yes_sample
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.yes-sample.entrypoints=websecure
      - traefik.http.routers.yes-sample.rule=Host(`yes-sample.local`)
    volumes:
      - .:/var/www
      - ./.docker/vhosts:/etc/apache2/sites-enabled
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      - web

  maildev:
    image: maildev/maildev
    container_name: maildev_yes_sample
    command: bin/maildev --smtp 25 --hide-extensions STARTTLS
    labels:
      - traefik.enable=true
      - traefik.http.routers.mail-yes-sample.entrypoints=websecure
      - traefik.http.routers.mail-yes-sample.rule=Host(`mail.yes-sample.local`)
      - traefik.http.services.mail-yes-sample.loadbalancer.server.port=1080
    networks:
      - web

volumes:
  db-data:

networks:
  web:
    external: true