name: Deploy Yes Sample
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-suggest --optimize-autoloader
    - name: Run tests
      run: bin/phpunit
    - name: Check if tests passed
      run: if [ -n "$(grep 'failures:' tests/log/junit.xml)" ]; then exit 1; fi

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Deploy in production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.APP_IP }}
        username: ${{ secrets.APP_USER }}
        key: ${{ secrets.APP_KEY }}
        script: |
          cd yes-sample
          git pull origin main
          docker-compose -f .docker/prod/docker-compose.yml --project-name yes-sample up -d --build --remove-orphans
          docker exec --user www-data -e APP_ENV=prod -e APP_DEBUG=0 web_yes_sample_prod composer install --no-dev --optimize-autoloader
          docker exec --user www-data web_yes_sample_prod bin/console doctrine:migrations:migrate --no-interaction
